package i18n

// Code generated by go generate; DO NOT EDIT.

const (
	ExpiredToken                = "ExpiredToken"
	InternalError               = "InternalError"
	InvalidRequest              = "InvalidRequest"
	ItemAlreadyExists           = "ItemAlreadyExists"
	ItemNotFound                = "ItemNotFound"
	PasswordMismatch            = "PasswordMismatch"
	TokenBlacklistAlreadyExists = "TokenBlacklistAlreadyExists"
	Unauthorized                = "Unauthorized"
	UserAlreadyExists           = "UserAlreadyExists"
	UserNotFound                = "UserNotFound"
)
