apiDoc: "/path/to/docs.html"
jwtSecret: "your_jwt_secret"
db:
  host: 'localhost'
  port: 3306
  database: 'your_db_name'
  username: 'your_db_user'
  password: 'your_db_password'
  verbose: false
  max_open_conns: 10
  max_idle_conns: 10
  conn_max_lifetime: 100